version: '3.9'
services:
  mysqldb:
    image: mysql:8.0
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql

  mysqldb-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - mysqldb
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/backup

networks:
  default:
    name: 'mysql-network'
    external: true
